version: "3.8"

services:
  apollo-graphql-server:
    container_name: apollo-graphql-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: rags:latest
    env_file:
      - .env
    volumes:
       - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    
    command: sh -c "npm install && npm start"

  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/schemas/01-airports-management.sql:/docker-entrypoint-initdb.d/01-airports-management.sql
      - ./src/db/schemas/02-airport.sql:/docker-entrypoint-initdb.d/02-airport.sql
      - ./src/db/schemas/03-passenger.sql:/docker-entrypoint-initdb.d/03-passenger.sql
      - ./src/db/schemas/04-airplane.sql:/docker-entrypoint-initdb.d/04-airplanes.sql
    ports:
      - "5432:5432"
    
volumes:
  db_data:



